version: '3.8'

services:
  sqldb:
    ports:
      - "1533:1433"
    environment:
      SA_PASSWORD: "P@ssw0rd!#"
      ACCEPT_EULA: "Y"

  nservicebusendpoint:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__ServiceBus=Data Source=sqldb;Database=Messaging;User ID=sa;Password=P@ssw0rd!#;Max Pool Size=100;Trust Server Certificate=True
      - ServiceBusTimeToWaitBeforeTriggeringCircuitBreaker=120
