version: '3.8'

services:
  sqldb:
    image: "mcr.microsoft.com/mssql/server"

  nservicebusendpoint:
    image: ${DOCKER_REGISTRY-}nservicebusendpoint
    build:
      context: .
      dockerfile: NServiceBusEndpoint/Dockerfile
    depends_on:
      - sqldb

  itops.healthmonitor:
    image: ${DOCKER_REGISTRY-}itopshealthmonitor
    build:
      context: .
      dockerfile: ITOps.HealthMonitor/Dockerfile