version: '3.4'

services:
  sqldb:
    image: "mcr.microsoft.com/mssql/server"

  nservicebusendpoint:
    image: ${DOCKER_REGISTRY-}nservicebusendpoint
    build:
      context: .
      dockerfile: NServiceBusEndpoint/Dockerfile
    depends_on:
      - sqldb
