version: '3.4'

services:
  sqldb:
    image: "mcr.microsoft.com/mssql/server"

  sales.ecommerce:
    image: ${DOCKER_REGISTRY-}salesecommerce
    build:
      context: .
      dockerfile: Showcase/Sales/Sales.ECommerce/Dockerfile
    depends_on:
      - sqldb
      - sales.ordering

  sales.ordering:
    image: ${DOCKER_REGISTRY-}salesordering
    build:
      context: .
      dockerfile: showcase/sales/sales.ordering/Dockerfile

